### ISSUE TITLE
Steam ID Oauth Support

### ISSUE THREAD

**Issue by Destructor** [kacx9c/steam#10]
Hi,

I use this for steamid retrieve: https://github.com/LavaToaster/IPS-SteamLoginMethod
Work for me Perfectly but Steam ID is stored on core_members on field steamid

This would allow you to automate the capture of the steamid via the login

Possible to add support for this field ?

![image](https://github.com/kacx9c/steam/assets/1570770/5351707c-9d47-40cf-8bb3-346f3cbc7b63)

**Comment by kacx9c** [comment]
@Destructor Does the linked login handler this still work on 4.7? In my experience, no. 

I'm working on a login handler. Once it's done I'll come back to this app and add support for pulling steam id from logins

**Comment by Destructor** [comment]
For me yes ...
![image](https://github.com/kacx9c/steam/assets/1570770/0de6f863-5d0c-4a22-b0f1-685338841a4f)
i use this since 4.5

**Comment by kacx9c** [comment]
@Destructor It's working for you because you still have the steam id column in core_members. That field, incidentally, isn't where the users steam id is stored for auth. I'll implement the feature to pull the steam id from the login table. Then I'll release a forked version of Lavo's repo that removes the requirement of the steam id column in core_members.

**Comment by Destructor** [comment]
Okay I hope to see it arrive quickly, because I use other addons on my game servers to recover this steamid for the VIP options and the store

Thanks again for your work :)

**Comment by Destructor** [comment]
> @Destructor It's working for you because you still have the steam id column in core_members. That field, incidentally, isn't where the users steam id is stored for auth. I'll implement the feature to pull the steam id from the login table. Then I'll release a forked version of Lavo's repo that removes the requirement of the steam id column in core_members.

for your commit, the steamid is not recognized, I think it is necessary to transfer it to the custom fields automatically via the login
![image](https://github.com/kacx9c/steam/assets/1570770/ff8125d3-13e4-4469-996f-e49f31d74f53)
![image](https://github.com/kacx9c/steam/assets/1570770/11addcce-f2fe-4808-a191-f79ad274e875)

**Comment by kacx9c** [comment]
It is not necessary. The token identifier in core login links is the Steam64 Id. If the user already existed in the Steam profiles table, the login task will not pick it up. If no profile exists, the login will be used to create the account. 

Could you detail what steps you performed to get that result? 

Workflow. 
- Custom field with a Steam id. User can manually update their cache. 
- Custom field with a Steam id, cleanup task will create the profile as it traverses users not in the Steam table. 
- User logs in via Steam, has Steam id stored in core login links. Login cleanup task will create profiles that do not exist in Steam profiles. 

This is all done with tasks to control the number of API requests for larger communities. API has limits. 

I still also need to finish member sync. 

I did a fair bit of testing this task and didn't see the result you are. Are there any errors being thrown? Check task logs?

**Comment by kacx9c** [comment]
Also, I appreciate the reports and working with me to get these issues resolved.

**Comment by Destructor** [comment]
I made a video for you to show you step by step via the steam login.

If I manually enter the steamid no problem.

https://streamable.com/8npsw1

**Comment by Destructor** [comment]
Maybe it's related to this for the steam login

`SELECT DISTINCT s.* FROM `steam_profiles` AS `s`  LEFT JOIN `core_members` AS `m` ON m.member_id = s.st_member_id  LEFT JOIN `core_groups` AS `g` ON (g.g_id = m.member_group_id OR g.g_id IN(m.mgroup_others)) WHERE g.steam_index=1 && g.steam_pull=1 && s.st_steamid<>'' AND s.st_personastate > 0 AND s.st_communityvisibilitystate != 1 ORDER BY RAND() LIMIT 0,5
IPS\Db\Exception: Unknown column 'g.steam_index' in 'where clause' (1054)
#0 /var/www/vhosts/clan-rmg.com/httpdocs/system/Db/Select.php(388): IPS\_Db->preparedQuery()
#1 /var/www/vhosts/clan-rmg.com/httpdocs/system/Db/Select.php(446): IPS\Db\_Select->runQuery()
#2 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/widgets/steamPlayerWidget.php(114): IPS\Db\_Select->rewind()
#3 /var/www/vhosts/clan-rmg.com/httpdocs/system/Widget/Widget.php(833): IPS\steam\widgets\_steamPlayerWidget->render()
#4 /var/www/vhosts/clan-rmg.com/httpdocs/system/Widget/Widget.php(888): IPS\_Widget->_render()
#5 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(19240): IPS\_Widget->__toString()
#6 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->widgetContainer()
#7 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(16404): IPS\Theme\_SandboxedTemplate->__call()
#8 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->sidebar()
#9 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(7535): IPS\Theme\_SandboxedTemplate->__call()
#10 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->globalTemplate()
#11 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(173): IPS\Theme\_SandboxedTemplate->__call()
#12 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Standard.php(113): IPS\_Dispatcher->finish()
#13 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Front.php(558): IPS\Dispatcher\_Standard->finish()
#14 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(155): IPS\Dispatcher\_Front->finish()
#15 /var/www/vhosts/clan-rmg.com/httpdocs/index.php(13): IPS\_Dispatcher->run()
#16 {main}`

BACKTRACE
`#0 /var/www/vhosts/clan-rmg.com/httpdocs/init.php(1033): IPS\_Log::log()
#1 /var/www/vhosts/clan-rmg.com/httpdocs/system/Widget/Widget.php(935): IPS\IPS::exceptionHandler()
#2 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(19240): IPS\_Widget->__toString()
#3 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->widgetContainer()
#4 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(16404): IPS\Theme\_SandboxedTemplate->__call()
#5 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->sidebar()
#6 /var/www/vhosts/clan-rmg.com/httpdocs/uploads/template_20_94a9d7649fb9cdbfc784d3516e61a717_global.php(7535): IPS\Theme\_SandboxedTemplate->__call()
#7 /var/www/vhosts/clan-rmg.com/httpdocs/system/Theme/SandboxedTemplate.php(61): IPS\Theme\Cache\class_core_front_global->globalTemplate()
#8 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(173): IPS\Theme\_SandboxedTemplate->__call()
#9 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Standard.php(113): IPS\_Dispatcher->finish()
#10 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Front.php(558): IPS\Dispatcher\_Standard->finish()
#11 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(155): IPS\Dispatcher\_Front->finish()
#12 /var/www/vhosts/clan-rmg.com/httpdocs/index.php(13): IPS\_Dispatcher->run()
#13 {main}`

**Comment by kacx9c** [comment]
@Destructor The errors relating to the group task aren't related, although I've added that to my things to fix. 

You're in some kind of limbo with rows in steam_profiles that are empty. How they got that way I don't know. Something that we'll need to investigate once your issue has been resolved.  In the steam_profiles table, you'll need to drop all rows that don't have a steam id. 

- The Cleanup task is looking for any member that has a value in a 'Steam ID' custom profile field that does NOT have a profile in steam_profiles. 
- The Login cleanup task is looking for any member using the steam login that does NOT have a profile in steam_profiles
- The SteamProfile task is looping through entries in the steam_profiles table and updating them. 
 
With all of those rows both existing, and not containing a steam id, they will never update. I'm not sure how they got into this state. Cleanup the steam_profiles table and if there is a way you can replicate the profile data going missing I'll make sure it's fixed pronto. Based on the above bullet points, the contents of the table will re-populate by itself. The table is essentially a cache designed to keep the number of steam API hits within limits. Allowing this application to work on any size community.

**Comment by kacx9c** [comment]
One other thing to note. This application no longer uses the steamid column in core_members. It was originally created by Lava's login, however IPS released an announcement that core tables are not to be touched, at least by a 3rd party application. You still need it there while you're using Lava's login, once I finish the fork it won't be used anymore and the column can be dropped.

**Comment by kacx9c** [comment]
Creating a new bug issue for this. Subject enhancement was made, bug has resulted from it.
