### ISSUE TITLE
Incompatible Invision Commerce

### ISSUE THREAD

**Issue by Destructor** [kacx9c/steam#11]
Hi,

Steam integration seems incompatible with invision ecommerce, blocked on error 500 page.

Nginx log:
`AH01071: Got error 'PHP message: PHP Fatal error: Declaration of IPS\\nexus\\Package\\_CustomField::buildHelper($value = null, $customValidationCode = null, ?IPS\\Content $content = null) must be compatible with IPS\\steam_hook_steamid::buildHelper($value = null, $customValidationCode = null, ?IPS\\Content $content = null, $flags = 0) in [/var/www/vhosts/clan-rmg.com/httpdocs/applications/nexus/sources/Package/CustomField.php](https://plesk.clan-rmg.com/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fapplications%2Fnexus%2Fsources%2FPackage&subscriptionId=1&file=CustomField.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) on line 208', referer: https://www.clan-rmg.com/admin/?app=nexus&module=store&controller=packages`

**Comment by kacx9c** [comment]
Where, specifically, are you getting this error? What page?

**Comment by Destructor** [comment]
On the store product page 
https://www.clan-rmg.com/store/product/2-vip/

and admincp (edit ou add product)

**Comment by kacx9c** [comment]
@Destructor You can keep track of changes https://github.com/kacx9c/steam/tree/develop if you would like to implement manually prior to a complete release.

**Comment by Destructor** [comment]
Tks :)
