### ISSUE TITLE
CSRF Protection Key

### ISSUE THREAD

**Issue by Blizzard098** [kacx9c/steam#13]
Hello,

I got an error when attempting to edit the settings in ACP:

**2S119/1 The CSRF protection key did not match. This may indicate a plugin or theme is out of date. Please contact technical support for more information.**

**Comment by kacx9c** [comment]
Which version are you using? Does this happen anywhere else in your ACP? Screenshot of the settings page you're trying to save? Blur out anything sensitive, API key, etc.

**Comment by Blizzard098** [comment]
> Which version are you using? Does this happen anywhere else in your ACP? Screenshot of the settings page you're trying to save? Blur out anything sensitive, API key, etc.

This doesn't happen anywhere else other than when I try and access the settings page for the Steam application. The error I pasted is the only thing shown on the page in that red error box.

**Comment by kacx9c** [comment]
@Blizzard098  Which version are you using? Both IPS and Steam?

**Comment by Blizzard098** [comment]
IPS Version 4.7.14 and Steam 3.0.1

**Comment by Blizzard098** [comment]
> IPS Version 4.7.14 and Steam 3.0.1

I have no idea what the issue was but it's working now. Question... do you think you'd be able to add compatibility for Steam Hex in the next update?

**Comment by kacx9c** [comment]
Could you close this as fixed and open a feature request?
