### ISSUE TITLE
No Steam in account settings

### ISSUE THREAD

**Issue by sp33ddinamo** [kacx9c/steam#14]
Hello, i have a problem: i don't have Steam in the account setting: 

![image](https://github.com/kacx9c/steam/assets/77357470/a8d227f8-0007-4098-8402-49b0932b8678)

Version used: 3.0.1

**Comment by Destructor** [comment]
Hi,
Currently there is no login handler, you must create a personalized profile field (Step 3 of the readme)

**Comment by sp33ddinamo** [comment]
![image](https://github.com/kacx9c/steam/assets/77357470/03644608-a134-4aa3-964a-06eb33077135)

but...
![image](https://github.com/kacx9c/steam/assets/77357470/dece9b11-e30f-4b8e-853c-0eee74ee303a)

and...
![image](https://github.com/kacx9c/steam/assets/77357470/ce11d110-af3f-4303-90d3-2dcd7ac4ad6f)

**Comment by kacx9c** [comment]
Log into your ACP -> Tasks and look at the last run of the tasks. 

Also, what message do you get if you use the options menu, on your profile page, to update your cache?

**Comment by sp33ddinamo** [comment]
![image](https://github.com/kacx9c/steam/assets/77357470/cebc72dc-fa58-4dbb-8ed7-644e6421f10d)

![image](https://github.com/kacx9c/steam/assets/77357470/ad8312d9-3ed8-42ee-a9c1-f53b01c82cf7)

![image](https://github.com/kacx9c/steam/assets/77357470/472cc47d-1f06-4db5-a3ee-ddfcd6e4e2ed)

**Comment by kacx9c** [comment]
Go to ACP -> Tasks and make sure the tasks are running. How many members are on your community? That will give me an idea of how long it should take the task to traverse your members. 

If you use the options menu on the Steam profile tab? What does the pop up say?

**Comment by kacx9c** [comment]
@sp33ddinamo Could you please provide details requested above?

**Comment by kacx9c** [comment]
@sp33ddinamo  any update?

**Comment by sp33ddinamo** [comment]
I have now noticed another problem. When I activate the steam application, 3 accounts are automatically created on the forum...
![image](https://github.com/kacx9c/steam/assets/77357470/2d675131-d71f-42ec-895f-52c28918348b)

**Comment by kacx9c** [comment]
@sp33ddinamo  Could you be a little more specific on how I could replicate this? What actions did you perform to get this result?

Also, have you tried removing and re-adding the random profiles block?
