### ISSUE TITLE
 Table 'steam_core_groups' doesn't exist

### ISSUE THREAD

**Issue by Calig** [kacx9c/steam#15]
I'm trying to upgrade from 2.1.12 > 3.0.1 and I get this error:

_Table 'forums.steam_core_groups' doesn't exist_

MySQL user has permissions to create and modify tables in the database.
Couldn't find a script where it would create such table.

**Comment by kacx9c** [comment]
@Calig The table should already exist. It is not something new in the upgrade. This must have been an issue before. 

<img width="569" alt="1212%h1205 80j3l" src="https://github.com/kacx9c/steam/assets/25600516/1186908a-3d28-4b62-ac64-08f02e84c003">

**Comment by Calig** [comment]
I do have **steam_groups** and **steam_profiles** tables.
![image](https://github.com/kacx9c/steam/assets/10079223/0707e922-1c33-42ff-ba29-703438ae349c)
![image](https://github.com/kacx9c/steam/assets/10079223/f8898a94-0411-4fc4-8942-4f549be01bc1)

What could I possibly do to fix it?

**Comment by kacx9c** [comment]
@Calig  I found the issue in the 3.0.0 upgrade step. Will push a fix shortly.

**Comment by kacx9c** [comment]
@Calig I've committed the fix, but there is one other issue that I'd like to further investigate and fix before building 3.0.2.

**Comment by Calig** [comment]
Awesome, thanks!
