### ISSUE TITLE
Register on ips not work

### ISSUE THREAD

**Issue by Destructor** [kacx9c/steam#19]
User cannot register 
 My error: 

`Error: Class "IPS\steam\extensions\core\MemberSync\Login" not found (0)
#0 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/extensions/core/MemberSync/memberSync.php(34): IPS\steam\extensions\core\MemberSync\_memberSync->onValidate()
#1 /var/www/vhosts/clan-rmg.com/httpdocs/system/Member/Member.php(4263): IPS\steam\extensions\core\MemberSync\_memberSync->onCreateAccount()
#2 /var/www/vhosts/clan-rmg.com/httpdocs/system/Member/Member.php(490): IPS\_Member->memberSync()
#3 /var/www/vhosts/clan-rmg.com/httpdocs/applications/core/modules/front/system/register.php(568): IPS\_Member->save()
#4 /var/www/vhosts/clan-rmg.com/httpdocs/applications/core/modules/front/system/register.php(242): IPS\core\modules\front\system\_register::_createMember()
#5 /var/www/vhosts/clan-rmg.com/httpdocs/applications/core/modules/front/system/register.php(105): IPS\core\modules\front\system\_register->_registrationForm()
#6 /var/www/vhosts/clan-rmg.com/httpdocs/init.php(934) : eval()'d code(27): IPS\core\modules\front\system\_register->manage()
#7 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Controller.php(118): IPS\core\modules\front\system\nexus_hook_register->manage()
#8 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(153): IPS\Dispatcher\_Controller->execute()
#9 /var/www/vhosts/clan-rmg.com/httpdocs/index.php(13): IPS\_Dispatcher->run()
#10 {main}`

`#0 /var/www/vhosts/clan-rmg.com/httpdocs/init.php(1036): IPS\_Log::log()
#1 [internal function]: IPS\IPS::exceptionHandler()
#2 {main}`

**Comment by Destructor** [comment]
@kacx9c do you have any idea where this comes from?

**Comment by kacx9c** [comment]
Duplicate https://github.com/kacx9c/steam/issues/18
