### ISSUE TITLE
EX256 - Error caused by application Steam Integration

### ISSUE THREAD

**Issue by iongeneral** [kacx9c/steam#20]
I've attempted to uninstall and reinstall the application with the same issue. IPS 4.4.10

`ErrorException: Class IPS\steam\Profile could not be loaded. Ensure it has been properly prefixed with an underscore and is in the correct namespace. (256)
#0 [internal function]: IPS\IPS::errorHandler(256, 'Class IPS\\steam...', '/home/evogamin/...', 670, Array)
#1 /home/evogamin/public_html/forums.evogaming.co.uk/init.php(670): trigger_error('Class IPS\\steam...', 256)
#2 [internal function]: IPS\IPS::autoloader('IPS\\steam\\Profi...')
#3 /home/evogamin/public_html/forums.evogaming.co.uk/applications/steam/extensions/core/Profile/profile.php(40): spl_autoload_call('IPS\\steam\\Profi...')
#4 /home/evogamin/public_html/forums.evogaming.co.uk/applications/core/modules/front/members/profile.php(222): IPS\steam\extensions\core\Profile\_profile->__construct(Object(IPS\Member))
#5 /home/evogamin/public_html/forums.evogaming.co.uk/init.php(820) : eval()'d code(17): IPS\core\modules\front\members\_profile->manage()
#6 /home/evogamin/public_html/forums.evogaming.co.uk/init.php(820) : eval()'d code(36): IPS\core\modules\front\members\trophies_hook_profile->manage()
#7 /home/evogamin/public_html/forums.evogaming.co.uk/system/Dispatcher/Controller.php(96): IPS\core\modules\front\members\steam_hook_steamDefault->manage()
#8 /home/evogamin/public_html/forums.evogaming.co.uk/applications/core/modules/front/members/profile.php(73): IPS\Dispatcher\_Controller->execute()
#9 /home/evogamin/public_html/forums.evogaming.co.uk/system/Dispatcher/Dispatcher.php(152): IPS\core\modules\front\members\_profile->execute()
#10 /home/evogamin/public_html/forums.evogaming.co.uk/index.php(13): IPS\_Dispatcher->run()
#11 {main}`
![firefox_Sox8PL9IbJ](https://github.com/kacx9c/steam/assets/69164415/00474a4d-ba36-4780-818e-22ab4815ed04)

**Comment by kacx9c** [comment]
This version was not tested on 4.4.x. It was developed and tested against 4.7.x. 4.7.x is the minimum supported version. Suggest updating to 4.7.

There is an older version of the code base that was developed on 4.4.x, but it is not in this repo.

**Comment by kacx9c** [comment]
This should be what you need. 
https://github.com/kacx9c/steam/releases/tag/2.1.13
