### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Destructor** [kacx9c/steam#8]
Hi,

I just reinstalled the application and currently in IPS version v4.7.11.1 and i have this error when I want to update the profiles.

`Error: Class "IPS\steam\API" not found (0)
#0 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/sources/Update/Update.php(156): IPS\steam\_Update->getSteamId()
#1 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/sources/Update/Update.php(117): IPS\steam\_Update->updateSingleProfileSummary()
#2 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/modules/front/steam/steamProfile.php(76): IPS\steam\_Update->updateFullProfile()
#3 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Controller.php(107): IPS\steam\modules\front\steam\_steamProfile->update()
#4 /var/www/vhosts/clan-rmg.com/httpdocs/applications/steam/modules/front/steam/steamProfile.php(49): IPS\Dispatcher\_Controller->execute()
#5 /var/www/vhosts/clan-rmg.com/httpdocs/system/Dispatcher/Dispatcher.php(153): IPS\steam\modules\front\steam\_steamProfile->execute()
#6 /var/www/vhosts/clan-rmg.com/httpdocs/index.php(13): IPS\_Dispatcher->run()
#7 {main}`

`#0 /var/www/vhosts/clan-rmg.com/httpdocs/init.php(1034): IPS\_Log::log()
#1 [internal function]: IPS\IPS::exceptionHandler()
#2 {main}`

And ACP > Community > Steam > Manage not exist:

![image](https://github.com/kacx9c/steam/assets/1570770/160c8f72-afb7-4ea8-899d-1d9056a00a53)

**Comment by kacx9c** [comment]
Manage was intentionally removed.
