### ISSUE TITLE
Settings error

### ISSUE THREAD

**Issue by burnyourfeelings** [kacx9c/steam#9]
![1](https://github.com/kacx9c/steam/assets/28813971/4a8e33f0-30b1-4592-adca-1e86be6af2bb)
![2](https://github.com/kacx9c/steam/assets/28813971/c956bcb3-8b82-4dd7-9721-8786dd396cdb)
Both throw the same error.

**Comment by Destructor** [comment]
https://github.com/kacx9c/steam/issues/8

Same issue

**Comment by kacx9c** [comment]
@Destructor  Can you look at your file structure and make sure /steam/sources/Api/Api.php exists?

**Comment by Destructor** [comment]
Yes exist

**Comment by kacx9c** [comment]
@Destructor I'm unable to replicate this. :( 
Can you try modifying line 386 of /steam/sources/Update/Update.php

Change `API` to `Api`

**Comment by Destructor** [comment]
> @Destructor I'm unable to replicate this. :( Can you try modifying line 386 of /steam/sources/Update/Update.php
> 
> Change `API` to `Api`

Fix with this modification

**Comment by kacx9c** [comment]
@burnyourfeelings   You can keep track of changes https://github.com/kacx9c/steam/tree/develop if you would like to implement manually prior to a complete release.
